### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by bodrych** [ventuary-lab/Waves-Augur#6]
**Sort** Description
![изображение](https://user-images.githubusercontent.com/1725999/64082952-d2c8a580-cd30-11e9-9f1f-b8189364e2ba.png)

**Comment by shama227** [comment]
Hello! Thanks for leaving a comment, we’ve fixed that typing issue, you can
check it in couple of minutes.

пн, 2 сент. 2019 г. в 1:23, Artem Badrtdinov <notifications@github.com>:
